### PR TITLE
Add support for logging in with help of third party API

### PR DESCRIPTION
**Pull request by djo011**
## Motivation for development of new feature
The current options for logging in did not support our needs. Our main identity provider(IdP) does not directly provide the desired claim for all users. Instead this claim can be retrieved through a third party API with a "token" from the main IdP.

## What has been changed/implemented ?
**goobi-viewer-core/src/main/java/io/goobi/viewer/controller/Configuration.java** - Added retrieval of new parameters from config_viewer.xml. Added the same parameters to the OIDC provider configuration.

**goobi-viewer-core/src/main/java/io/goobi/viewer/controller/JsonTools.java** - Added new helper method to find a value in a nested json object.

**goobi-viewer-core/src/main/java/io/goobi/viewer/model/security/authentication/OpenIdProvider.java** - Extend current OIDC login with option to use a third party API to get claim used for identifying users.

**goobi-viewer-core/src/main/java/io/goobi/viewer/servlets/openid/OAuthServlet.java** - Extend the OAuthServlet to handle login with the help of third party API. After successfully recieving and verifying ID-token from IdP. Check if required claim ("email") is present in ID-token. If not, use third party API to get this information. The request to the third party API is a POST request with API Key and a JSON body. The data in the JSON body can be configured via the earlier mentioned parameters.

**goobi-viewer-core/src/test/java/io/goobi/viewer/controller/ConfigurationTest.java and goobi-viewer-core/src/test/resources/config_viewer.test.xml** - Update with basic test functionality.

**New configurable parameters** 
tPLoginUrl - The url for the desired API to use in third party login method. 

tPLoginApiKey - The API key in third party login method is passed in the header. Parameter must specify key name and the actual key value. Example: "X-API-Key abcdef1234"

tPLoginScope - The name of the field in the response from the main identity provider that contains data to be used in request to third party API.

tPLoginReqParamDef - The name of the key in the JSON formatted body of the request to be sent to the third party API.

tPLoginClaim - The name of the key in the JSON-response from the third party API that contains the claim used for logging in.

## Final comments
The implementation is meant to be as generic and configurable as possible, while still meeting the requirements of our needs. This can hopefully be reused by others, but there is a slight chance this might be an edge case for login options.

### CODE REVIEW

**Comment by Keelhaul** [comment]
Hi Daniel,

Thank you for your contribution! Could you please add/change a few things before we can merge it:
1) Add some description to your configurable parameters (we'll have to add them to our manual: https://docs.goobi.io/goobi-viewer-en/conf/1/5/1#config_viewer.xml).
2) Use camelCaseVariableNames without underscores, because our Sonar/Checkstyle quality checks don't take kindly to those.

Thanks,
Andrey

**Comment by djo011** [comment]
Hi Andrey,

I have now updated the PR with description of the new parameters and changed names of variables to strictly follow camelCaseVariableNaming.

Please let me know if there is anything else that needs attention!

Best,
Daniel

**Comment by djo011** [comment]
Hi Andrey,

Are there any updates on the status of this pull request? Do you need me to update the code to the newest develop before merging or is it ok?

Best,
Daniel

**Comment by Keelhaul** [comment]
Hi Daniel,

Unfortunately, we haven't gotten around to merge it yet. But in the long run, we're updating viewer-core for Tomcat 10 compatibility (due in early 2025), and the future of Apache Oltu as our OAuth2 lib is uncertain due to it no longer being maintained and not using jakarta.servlet.* packages.

We'll try to merge your code to the current version ASAP and then see how we move forward.

Best,
Andrey

**Comment by Keelhaul** [comment]
Hi Daniel,

Your PR should be merged now. Thank you for the contribution :)

**Pull request merged**
